use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::cli::ToolSpec;
use crate::error::RunxError;
use crate::platform::Target;
use crate::provider;
use crate::version::VersionSpec;

const LOCKFILE_NAME: &str = ".runxrc.lock";

/// A locked tool entry with exact version and download metadata.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedTool {
    pub version: String,
    pub url: String,
    pub sha256: Option<String>,
}

/// The full lockfile: a map of tool names to locked entries.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct Lockfile {
    #[serde(flatten)]
    pub tools: BTreeMap<String, LockedTool>,
}

/// Find the lockfile by walking up from `start_dir`.
pub fn find_lockfile(start_dir: &Path) -> Option<PathBuf> {
    let mut dir = start_dir.to_path_buf();
    loop {
        let candidate = dir.join(LOCKFILE_NAME);
        if candidate.is_file() {
            return Some(candidate);
        }
        if !dir.pop() {
            return None;
        }
    }
}

/// Load a lockfile from disk.
pub fn load_lockfile(path: &Path) -> Result<Lockfile, RunxError> {
    let contents = std::fs::read_to_string(path).map_err(RunxError::Io)?;
    let lockfile: Lockfile = toml::from_str(&contents).map_err(|e| {
        RunxError::Config(crate::config::ConfigError::Parse {
            path: path.to_path_buf(),
            reason: e.to_string(),
        })
    })?;
    Ok(lockfile)
}

/// Generate a lockfile from tool specs by resolving each against upstream.
pub fn generate_lockfile(tools: &[ToolSpec], target: &Target) -> Result<Lockfile, RunxError> {
    let mut locked = BTreeMap::new();

    for spec in tools {
        let prov = provider::get_provider(&spec.name)?;

        let version_spec = match &spec.version {
            Some(v) => {
                v.parse::<VersionSpec>()
                    .map_err(|e| provider::ProviderError::ResolutionFailed {
                        tool: spec.name.clone(),
                        reason: e,
                    })?
            }
            None => VersionSpec::Latest,
        };

        eprintln!("Resolving {}@{}...", spec.name, version_spec);
        let version = prov.resolve_version(&version_spec, target)?;
        let url = prov.download_url(&version, target)?;

        eprintln!("Locked {} → {}", spec.name, version);

        locked.insert(
            spec.name.clone(),
            LockedTool {
                version: version.to_string(),
                url,
                sha256: None,
            },
        );
    }

    Ok(Lockfile { tools: locked })
}

/// Write a lockfile to disk.
pub fn write_lockfile(lockfile: &Lockfile, path: &Path) -> Result<(), RunxError> {
    let content = toml::to_string_pretty(lockfile)
        .map_err(|e| RunxError::Io(std::io::Error::other(e.to_string())))?;

    let mut output = String::from(
        "# Auto-generated by runx. Do not edit.\n# Commit this file to version control.\n\n",
    );
    output.push_str(&content);

    std::fs::write(path, output).map_err(RunxError::Io)?;
    Ok(())
}

/// Execute the `runx lock` subcommand.
pub fn run(update: bool) -> Result<(), RunxError> {
    let cwd = std::env::current_dir().map_err(RunxError::NoCwd)?;
    let target = Target::detect().map_err(RunxError::UnsupportedPlatform)?;

    // Load .runxrc to get tool specs
    let cfg = crate::config::load_config(&cwd)?;
    if cfg.tools.is_empty() {
        eprintln!("No tools specified in .runxrc. Nothing to lock.");
        return Ok(());
    }

    let lockfile_path = cwd.join(LOCKFILE_NAME);

    if lockfile_path.exists() && !update {
        eprintln!(
            ".runxrc.lock already exists.\n  Use `runx lock --update` to re-resolve and update it."
        );
        return Ok(());
    }

    let lockfile = generate_lockfile(&cfg.tools, &target)?;
    write_lockfile(&lockfile, &lockfile_path)?;

    println!("Wrote {LOCKFILE_NAME}");
    for (name, locked) in &lockfile.tools {
        println!("  {name} = {}", locked.version);
    }
    println!("\nCommit this file to version control for reproducible builds.");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lockfile_serialize_roundtrip() {
        let mut tools = BTreeMap::new();
        tools.insert(
            "node".to_string(),
            LockedTool {
                version: "22.11.0".to_string(),
                url: "https://example.com/node.tar.gz".to_string(),
                sha256: Some("abc123".to_string()),
            },
        );
        let lockfile = Lockfile { tools };

        let serialized = toml::to_string_pretty(&lockfile).unwrap();
        let deserialized: Lockfile = toml::from_str(&serialized).unwrap();

        assert_eq!(deserialized.tools["node"].version, "22.11.0");
        assert_eq!(
            deserialized.tools["node"].url,
            "https://example.com/node.tar.gz"
        );
        assert_eq!(deserialized.tools["node"].sha256.as_deref(), Some("abc123"));
    }

    #[test]
    fn test_lockfile_default_empty() {
        let lockfile = Lockfile::default();
        assert!(lockfile.tools.is_empty());
    }

    #[test]
    fn test_find_lockfile_not_found() {
        let dir = tempfile::tempdir().unwrap();
        assert!(find_lockfile(dir.path()).is_none());
    }

    #[test]
    fn test_find_lockfile_in_current_dir() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(LOCKFILE_NAME);
        std::fs::write(&path, "[node]\nversion = \"22.0.0\"\nurl = \"x\"\n").unwrap();
        assert_eq!(find_lockfile(dir.path()), Some(path));
    }

    #[test]
    fn test_find_lockfile_walks_up() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(LOCKFILE_NAME);
        std::fs::write(&path, "[node]\nversion = \"22.0.0\"\nurl = \"x\"\n").unwrap();

        let child = dir.path().join("sub");
        std::fs::create_dir(&child).unwrap();
        assert_eq!(find_lockfile(&child), Some(path));
    }

    #[test]
    fn test_load_lockfile() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(LOCKFILE_NAME);
        std::fs::write(
            &path,
            "[node]\nversion = \"22.11.0\"\nurl = \"https://example.com/node.tar.gz\"\n",
        )
        .unwrap();

        let lockfile = load_lockfile(&path).unwrap();
        assert_eq!(lockfile.tools["node"].version, "22.11.0");
    }

    #[test]
    fn test_write_lockfile() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join(LOCKFILE_NAME);

        let mut tools = BTreeMap::new();
        tools.insert(
            "go".to_string(),
            LockedTool {
                version: "1.22.0".to_string(),
                url: "https://go.dev/dl/go1.22.0.tar.gz".to_string(),
                sha256: None,
            },
        );
        let lockfile = Lockfile { tools };

        write_lockfile(&lockfile, &path).unwrap();

        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("# Auto-generated by runx"));
        assert!(content.contains("version = \"1.22.0\""));
    }
}
